version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
  adminer:
    image: adminer
    ports:
      - 8080:8080
  web:
    build: .
    command: bash ./bin/start
    volumes:
      - .:/webapp
    ports:
      - 3000:3000
    depends_on:
      - db
